# breweries index
GET http://localhost:3000/breweries?state=washington

### breweries destroy
DELETE http://localhost:3000/breweries/28

### breweries show
GET http://localhost:3000/breweries/29

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test",
  "email": "test@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}